# **Imports**

In [1]:

from earthscape.utils.constants import VERSION, ASSETS_DIR, MODEL_DIR
import os
import glob
import numpy as np
import pandas as pd
from scipy.stats import t
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from matplotlib.patches import Patch
import seaborn as sns

# **Setup**

In [33]:
#############################################
# Setup input and output directories & paths
#############################################

# directory of experiments
exp_dir = r'../experiments/baselines/segmentation'

# single modality experiments...
single_root = os.path.join(exp_dir, 'single')
single_dirs = glob.glob(f"{single_root}/*")

# multi-scale modality experiments...
ms_root = os.path.join(exp_dir, 'multiscale')
ms_dirs = glob.glob(f"{ms_root}/*")

# multimodal experiments modalities...
mm_root = os.path.join(exp_dir, 'multimodal')
mm_dirs = glob.glob(f"{mm_root}/*")

# output directory for visualizations...
assets_dir = os.path.join(exp_dir.replace(MODEL_DIR, ASSETS_DIR))
if not os.path.isdir(assets_dir):
    os.makedirs(assets_dir)

# **Global Model Performance**

## *Single Modality Experiment Compilation*

In [41]:
##################################################
# Compile Global Performance Metrics - Single
##################################################

# output path for global summary
output_path = os.path.join(assets_dir, 'single_global.csv')


##### compile global in- & cross-domain data...
# initialize df
df = pd.DataFrame(columns=['model', 'encoder', 'input'])

# collect global data from all experiments...
for idx, d in enumerate(single_dirs):
    
    # skip any files in root directory...
    if os.path.isfile(d):
        continue
    
    # metadata of model name & modality input...
    meta = os.path.basename(d)
    meta = meta.split('_')
    model_name = meta[0].split('-')[0]
    encoder_name = meta[0].split('-')[1]
    modalities = meta[1]

    # in-domain...
    id_global_path = os.path.join(d, 'id_overall.csv')
    id = pd.read_csv(id_global_path)
    id.columns = [col +' (id)' for col in id.columns]
    
    # cross-domain...
    cd_global_path = os.path.join(d, 'cd_overall.csv')
    cd = pd.read_csv(cd_global_path)
    cd.columns = [col +' (cd)' for col in cd.columns]

    # merge datasets...
    df.loc[idx, 'model'] = model_name
    df.loc[idx, 'encoder'] = encoder_name
    df.loc[idx, 'input'] = modalities
    df.loc[idx, id.columns] = id.values
    df.loc[idx, cd.columns] = cd.values


# save & display...
df.to_csv(output_path, index=False)
df.sort_values('micro_iou (id)', ascending=False).head()

,model,encoder,input,macro_iou (id),macro_dice (id),macro_precision (id),macro_recall (id),micro_iou (id),micro_dice (id),micro_precision (id),...,macro_iou (cd),macro_dice (cd),macro_precision (cd),macro_recall (cd),micro_iou (cd),micro_dice (cd),micro_precision (cd),micro_recall (cd),mean_hd (cd),mean_hd95 (cd)
70,segformer,mitb2,dem,0.489031,0.550684,0.616618,0.559820,0.780764,0.876887,0.876887,...,0.383654,0.440898,0.513953,0.461956,0.687296,0.814671,0.814671,0.814671,98.951378,82.651987
28,deeplabv3p,resnet50,s-5,0.475116,0.535211,0.595916,0.547041,0.766712,0.867953,0.867953,...,0.411731,0.467860,0.524283,0.480035,0.738597,0.849647,0.849647,0.849647,96.460381,79.841961
35,segformer,mitb0,dem,0.473483,0.535988,0.596516,0.552825,0.765678,0.867290,0.867290,...,0.395051,0.447822,0.515335,0.471019,0.719141,0.836628,0.836628,0.836628,97.559263,80.890456
133,unet,resnet18,s-5,0.450994,0.507200,0.576880,0.517709,0.763736,0.866044,0.866044,...,0.400427,0.454874,0.513998,0.466545,0.745687,0.854319,0.854319,0.854319,100.371829,79.895820
24,deeplabv3p,resnet50,s-10,0.480606,0.539703,0.603613,0.551728,0.762266,0.865098,0.865098,...,0.415956,0.468685,0.526025,0.482552,0.729383,0.843518,0.843518,0.843518,94.331813,77.795653

## *Multi-scale Experiment Compilation*

In [42]:
##################################################
# Compile Global Performance Metrics - Multiscale
##################################################

# output path for global summary
output_path = os.path.join(assets_dir, 'multiscale_global.csv')


##### compile global in- & cross-domain data...
# initialize df
df = pd.DataFrame(columns=['model', 'encoder', 'input'])

# collect global data from all experiments...
for idx, d in enumerate(ms_dirs):
    
    # skip any files in root directory...
    if os.path.isfile(d):
        continue
    
    # metadata of model name & modality input...
    meta = os.path.basename(d)
    meta = meta.split('_')
    model_name = meta[0].split('-')[0]
    encoder_name = meta[0].split('-')[1]
    modalities = meta[1]

    # in-domain...
    id_global_path = os.path.join(d, 'id_overall.csv')
    id = pd.read_csv(id_global_path)
    id.columns = [col +' (id)' for col in id.columns]
    
    # cross-domain...
    cd_global_path = os.path.join(d, 'cd_overall.csv')
    cd = pd.read_csv(cd_global_path)
    cd.columns = [col +' (cd)' for col in cd.columns]

    # merge datasets...
    df.loc[idx, 'model'] = model_name
    df.loc[idx, 'encoder'] = encoder_name
    df.loc[idx, 'input'] = modalities
    df.loc[idx, id.columns] = id.values
    df.loc[idx, cd.columns] = cd.values


# save & display...
df.to_csv(output_path, index=False)
df.sort_values('micro_iou (id)', ascending=False).head()

,model,encoder,input,macro_iou (id),macro_dice (id),macro_precision (id),macro_recall (id),micro_iou (id),micro_dice (id),micro_precision (id),...,macro_iou (cd),macro_dice (cd),macro_precision (cd),macro_recall (cd),micro_iou (cd),micro_dice (cd),micro_precision (cd),micro_recall (cd),mean_hd (cd),mean_hd95 (cd)
3,deeplabv3p,resnet50,s-ms,0.484805,0.544435,0.607743,0.557811,0.776282,0.874052,0.874052,...,0.423413,0.479090,0.531074,0.497234,0.749290,0.856679,0.856679,0.856679,96.302821,79.824426
13,segformer,mitb2,s-ms,0.487949,0.549833,0.613054,0.563375,0.774502,0.872923,0.872923,...,0.419074,0.477022,0.533200,0.494685,0.739963,0.850550,0.850550,0.850550,96.395804,79.443703
2,deeplabv3p,resnet50,prc-ms,0.482729,0.547748,0.609042,0.559647,0.770579,0.870426,0.870426,...,0.426060,0.487663,0.548741,0.506200,0.735658,0.847699,0.847699,0.847699,95.392149,78.768571
8,segformer,mitb0,s-ms,0.483059,0.545057,0.608899,0.556748,0.768890,0.869348,0.869348,...,0.413311,0.470766,0.525280,0.488505,0.737110,0.848662,0.848662,0.848662,96.600286,80.068046
18,unet,resnet18,s-ms,0.466991,0.526488,0.594906,0.536720,0.768451,0.869067,0.869067,...,0.422019,0.476414,0.529837,0.486034,0.763551,0.865925,0.865925,0.865925,99.694616,79.001542

## *Multimodal Experiment Compilation*

In [43]:
##################################################
# Compile Global Performance Metrics - Multimodal
##################################################

# output path for global summary
output_path = os.path.join(assets_dir, 'multimodal_global.csv')


##### compile global in- & cross-domain data...
# initialize df
df = pd.DataFrame(columns=['model', 'encoder', 'input'])

# collect global data from all experiments...
for idx, d in enumerate(mm_dirs):
    
    # skip any files in root directory...
    if os.path.isfile(d):
        continue
    
    # metadata of model name & modality input...
    meta = os.path.basename(d)
    meta = meta.split('_')
    model_name = meta[0].split('-')[0]
    encoder_name = meta[0].split('-')[1]
    modalities = meta[1]

    # in-domain...
    id_global_path = os.path.join(d, 'id_overall.csv')
    id = pd.read_csv(id_global_path)
    id.columns = [col +' (id)' for col in id.columns]
    
    # cross-domain...
    cd_global_path = os.path.join(d, 'cd_overall.csv')
    cd = pd.read_csv(cd_global_path)
    cd.columns = [col +' (cd)' for col in cd.columns]

    # merge datasets...
    df.loc[idx, 'model'] = model_name
    df.loc[idx, 'encoder'] = encoder_name
    df.loc[idx, 'input'] = modalities
    df.loc[idx, id.columns] = id.values
    df.loc[idx, cd.columns] = cd.values


# save & display...
df.to_csv(output_path, index=False)
df.sort_values('micro_iou (id)', ascending=False).head()

,model,encoder,input,macro_iou (id),macro_dice (id),macro_precision (id),macro_recall (id),micro_iou (id),micro_dice (id),micro_precision (id),...,macro_iou (cd),macro_dice (cd),macro_precision (cd),macro_recall (cd),micro_iou (cd),micro_dice (cd),micro_precision (cd),micro_recall (cd),mean_hd (cd),mean_hd95 (cd)
19,unet,resnet18,ep-ms+prc-ms+s-ms,0.498217,0.559482,0.620749,0.569213,0.801956,0.890095,0.890095,...,0.421719,0.479869,0.526230,0.494885,0.759270,0.863165,0.863165,0.863165,95.092682,75.278611
5,deeplabv3p,resnet50,prc-ms+s-ms,0.512490,0.575337,0.635278,0.583955,0.799682,0.888693,0.888692,...,0.463329,0.523455,0.574666,0.538645,0.776328,0.874082,0.874082,0.874082,88.370076,71.160174
23,unet,resnet18,prc-ms+s-ms,0.495536,0.557914,0.615054,0.570558,0.798920,0.888222,0.888222,...,0.417799,0.476382,0.529127,0.495688,0.749643,0.856909,0.856910,0.856910,97.683011,77.606396
1,deeplabv3p,resnet50,ep-ms+prc-ms+s-ms,0.517403,0.579121,0.642594,0.589566,0.798666,0.888065,0.888065,...,0.450268,0.509555,0.569154,0.523452,0.761464,0.864581,0.864581,0.864581,91.516889,73.818294
3,deeplabv3p,resnet50,ep-ms+s-ms+sds-ms,0.500392,0.561720,0.618571,0.571191,0.798437,0.887923,0.887923,...,0.443377,0.502536,0.556308,0.517657,0.769382,0.869662,0.869662,0.869662,90.872558,73.812591

## *All Experiments Compilation*

In [44]:
##################################################
# Compile All Global Experiments
##################################################

# paths to single, multi-scale, & multimodal compilations...
single_path = os.path.join(assets_dir, "single_global.csv")
ms_path = os.path.join(assets_dir, "multiscale_global.csv")
mm_path = os.path.join(assets_dir, "multimodal_global.csv")

# output path
output_path = os.path.join(assets_dir, 'compiled_global.csv')


##### compile data...
df_list = []
df_list.append(pd.read_csv(single_path))
df_list.append(pd.read_csv(ms_path))
df_list.append(pd.read_csv(mm_path))

df = pd.concat(df_list)
df.reset_index(drop=True, inplace=True)

df.to_csv(output_path, index=False)
df.sort_values('micro_iou (id)', ascending=False).head()

,model,encoder,input,macro_iou (id),macro_dice (id),macro_precision (id),macro_recall (id),micro_iou (id),micro_dice (id),micro_precision (id),...,macro_iou (cd),macro_dice (cd),macro_precision (cd),macro_recall (cd),micro_iou (cd),micro_dice (cd),micro_precision (cd),micro_recall (cd),mean_hd (cd),mean_hd95 (cd)
179,unet,resnet18,ep-ms+prc-ms+s-ms,0.498217,0.559482,0.620749,0.569213,0.801956,0.890095,0.890095,...,0.421719,0.479869,0.526230,0.494885,0.759270,0.863165,0.863165,0.863165,95.092682,75.278611
165,deeplabv3p,resnet50,prc-ms+s-ms,0.512490,0.575337,0.635278,0.583955,0.799682,0.888693,0.888692,...,0.463329,0.523455,0.574666,0.538645,0.776328,0.874082,0.874082,0.874082,88.370076,71.160174
183,unet,resnet18,prc-ms+s-ms,0.495536,0.557914,0.615054,0.570558,0.798920,0.888222,0.888222,...,0.417799,0.476382,0.529127,0.495688,0.749643,0.856909,0.856910,0.856910,97.683011,77.606396
161,deeplabv3p,resnet50,ep-ms+prc-ms+s-ms,0.517403,0.579121,0.642594,0.589566,0.798666,0.888065,0.888065,...,0.450268,0.509555,0.569154,0.523452,0.761464,0.864581,0.864581,0.864581,91.516889,73.818294
163,deeplabv3p,resnet50,ep-ms+s-ms+sds-ms,0.500392,0.561720,0.618571,0.571191,0.798437,0.887923,0.887923,...,0.443377,0.502536,0.556308,0.517657,0.769382,0.869662,0.869662,0.869662,90.872558,73.812591

## *Visualizations*

# **Global Class Performance**

## *Single Modality Experiment Compilation*

In [80]:
##################################################
# Compile Per-Class Performance Metrics - Single
##################################################

# output path for compilation
output_path = os.path.join(assets_dir, 'single_class.csv')


##### compile in- & cross-domain data...
# initialize df
df_all = pd.DataFrame(columns=['model', 'encoder', 'input'])

# collect data from all experiments...
idx = 0
for d in single_dirs:
    
    # skip any files in root directory...
    if os.path.isfile(d):
        continue
    
    # metadata of model name & modality input...
    meta = os.path.basename(d)
    meta = meta.split('_')
    model_name = meta[0].split('-')[0]
    encoder_name = meta[0].split('-')[1]
    modalities = meta[1]

    # in-domain...
    id_global_path = os.path.join(d, 'id_overall_class.csv')
    id = pd.read_csv(id_global_path)
    id.set_index('class', inplace=True, drop=True)
    id.columns = [col +' (id)' for col in id.columns]
    
    # cross-domain...
    cd_global_path = os.path.join(d, 'cd_overall_class.csv')
    cd = pd.read_csv(cd_global_path)
    cd.set_index('class', inplace=True, drop=True)
    cd.columns = [col +' (cd)' for col in cd.columns]

    # merge in- & cross-domain subsets...
    df = pd.merge(left=id, right=cd, how='left', left_index=True, right_index=True)
    df.reset_index(inplace=True)

    # combine datasets...
    df_all = pd.concat([df_all, df], ignore_index=True, axis=0)
    df_all.loc[idx:idx+(len(df)), 'model'] = model_name
    df_all.loc[idx:idx+(len(df)), 'encoder'] = encoder_name
    df_all.loc[idx:idx+(len(df)), 'input'] = modalities

    idx += len(df)

# save & display...
df_all.to_csv(output_path, index=False)
df_all.head()

,model,encoder,input,class,gt_support (id),pred_support (id),gt_num_images (id),pred_num_images (id),tp (id),fp (id),...,macro_iou (cd),macro_dice (cd),macro_precision (cd),macro_recall (cd),mean_hd (cd),mean_hd95 (cd),micro_iou (cd),micro_dice (cd),micro_precision (cd),micro_recall (cd)
0,deeplabv3p,resnet50,dem,Qaf,10183.0,0.0,10.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000
1,deeplabv3p,resnet50,dem,Qal,8361713.0,7536136.0,947.0,928.0,5980234.0,1555902.0,...,0.137092,0.188426,0.314983,0.180292,141.442329,126.829787,0.228576,0.372099,0.608144,0.268055
2,deeplabv3p,resnet50,dem,Qat,388848.0,268789.0,61.0,60.0,94148.0,174641.0,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000
3,deeplabv3p,resnet50,dem,Qc,16237424.0,17202215.0,748.0,807.0,14663487.0,2538728.0,...,0.213697,0.275945,0.229029,0.435821,130.693717,111.436685,0.434113,0.605410,0.445544,0.944196
4,deeplabv3p,resnet50,dem,Qca,7202703.0,5861922.0,431.0,419.0,3971679.0,1890243.0,...,0.028692,0.045314,0.126181,0.039797,172.521181,158.150522,0.069393,0.129781,0.146740,0.116336

## *Multi-scale Experiment Compilation*

In [81]:
##################################################
# Compile Per-Class Performance Metrics - Multi-scale
##################################################

# output path for compilation
output_path = os.path.join(assets_dir, 'multiscale_class.csv')


##### compile in- & cross-domain data...
# initialize df
df_all = pd.DataFrame(columns=['model', 'encoder', 'input'])

# collect data from all experiments...
idx = 0
for d in ms_dirs:
    
    # skip any files in root directory...
    if os.path.isfile(d):
        continue
    
    # metadata of model name & modality input...
    meta = os.path.basename(d)
    meta = meta.split('_')
    model_name = meta[0].split('-')[0]
    encoder_name = meta[0].split('-')[1]
    modalities = meta[1]

    # in-domain...
    id_global_path = os.path.join(d, 'id_overall_class.csv')
    id = pd.read_csv(id_global_path)
    id.set_index('class', inplace=True, drop=True)
    id.columns = [col +' (id)' for col in id.columns]
    
    # cross-domain...
    cd_global_path = os.path.join(d, 'cd_overall_class.csv')
    cd = pd.read_csv(cd_global_path)
    cd.set_index('class', inplace=True, drop=True)
    cd.columns = [col +' (cd)' for col in cd.columns]

    # merge in- & cross-domain subsets...
    df = pd.merge(left=id, right=cd, how='left', left_index=True, right_index=True)
    df.reset_index(inplace=True)

    # combine datasets...
    df_all = pd.concat([df_all, df], ignore_index=True, axis=0)
    df_all.loc[idx:idx+(len(df)), 'model'] = model_name
    df_all.loc[idx:idx+(len(df)), 'encoder'] = encoder_name
    df_all.loc[idx:idx+(len(df)), 'input'] = modalities

    idx += len(df)

# save & display...
df_all.to_csv(output_path, index=False)
df_all.head()

,model,encoder,input,class,gt_support (id),pred_support (id),gt_num_images (id),pred_num_images (id),tp (id),fp (id),...,macro_iou (cd),macro_dice (cd),macro_precision (cd),macro_recall (cd),mean_hd (cd),mean_hd95 (cd),micro_iou (cd),micro_dice (cd),micro_precision (cd),micro_recall (cd)
0,deeplabv3p,resnet50,ep-ms,Qaf,10183.0,0.0,10.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000
1,deeplabv3p,resnet50,ep-ms,Qal,8361713.0,8199411.0,947.0,1054.0,6680436.0,1518975.0,...,0.303881,0.375916,0.371760,0.473266,120.295557,104.006573,0.514143,0.679121,0.552783,0.880316
2,deeplabv3p,resnet50,ep-ms,Qat,388848.0,539226.0,61.0,109.0,172118.0,367108.0,...,0.016082,0.024768,0.063236,0.026466,178.579663,167.108281,0.045650,0.087315,0.067224,0.124535
3,deeplabv3p,resnet50,ep-ms,Qc,16237424.0,15833644.0,748.0,706.0,13838003.0,1995641.0,...,0.004168,0.006639,0.065462,0.004968,224.932480,206.073399,0.005830,0.011593,0.433847,0.005875
4,deeplabv3p,resnet50,ep-ms,Qca,7202703.0,5329902.0,431.0,371.0,3621076.0,1708826.0,...,0.008422,0.011123,0.017571,0.013183,185.029811,175.860970,0.020005,0.039224,0.168537,0.022195

## *Multimodal Experiment Compilation*

In [82]:
##################################################
# Compile Per-Class Performance Metrics - Multimodal
##################################################

# output path for compilation
output_path = os.path.join(assets_dir, 'multimodal_class.csv')


##### compile in- & cross-domain data...
# initialize df
df_all = pd.DataFrame(columns=['model', 'encoder', 'input'])

# collect data from all experiments...
idx = 0
for d in mm_dirs:
    
    # skip any files in root directory...
    if os.path.isfile(d):
        continue
    
    # metadata of model name & modality input...
    meta = os.path.basename(d)
    meta = meta.split('_')
    model_name = meta[0].split('-')[0]
    encoder_name = meta[0].split('-')[1]
    modalities = meta[1]

    # in-domain...
    id_global_path = os.path.join(d, 'id_overall_class.csv')
    id = pd.read_csv(id_global_path)
    id.set_index('class', inplace=True, drop=True)
    id.columns = [col +' (id)' for col in id.columns]
    
    # cross-domain...
    cd_global_path = os.path.join(d, 'cd_overall_class.csv')
    cd = pd.read_csv(cd_global_path)
    cd.set_index('class', inplace=True, drop=True)
    cd.columns = [col +' (cd)' for col in cd.columns]

    # merge in- & cross-domain subsets...
    df = pd.merge(left=id, right=cd, how='left', left_index=True, right_index=True)
    df.reset_index(inplace=True)

    # combine datasets...
    df_all = pd.concat([df_all, df], ignore_index=True, axis=0)
    df_all.loc[idx:idx+(len(df)), 'model'] = model_name
    df_all.loc[idx:idx+(len(df)), 'encoder'] = encoder_name
    df_all.loc[idx:idx+(len(df)), 'input'] = modalities

    idx += len(df)

# save & display...
df_all.to_csv(output_path, index=False)
df_all.head()

,model,encoder,input,class,gt_support (id),pred_support (id),gt_num_images (id),pred_num_images (id),tp (id),fp (id),...,macro_iou (cd),macro_dice (cd),macro_precision (cd),macro_recall (cd),mean_hd (cd),mean_hd95 (cd),micro_iou (cd),micro_dice (cd),micro_precision (cd),micro_recall (cd)
0,deeplabv3p,resnet50,dem+rgb,Qaf,10183.0,0.0,10.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000
1,deeplabv3p,resnet50,dem+rgb,Qal,8361713.0,7783900.0,947.0,945.0,6189999.0,1593901.0,...,0.021206,0.033100,0.132261,0.023510,158.595136,148.114965,0.024281,0.047411,0.734611,0.024496
2,deeplabv3p,resnet50,dem+rgb,Qat,388848.0,201869.0,61.0,55.0,74447.0,127422.0,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000
3,deeplabv3p,resnet50,dem+rgb,Qc,16237424.0,15958691.0,748.0,781.0,14308856.0,1649835.0,...,0.084895,0.124819,0.287199,0.112029,172.168721,156.376829,0.133184,0.235061,0.611706,0.145483
4,deeplabv3p,resnet50,dem+rgb,Qca,7202703.0,6794139.0,431.0,424.0,4537760.0,2256379.0,...,0.022104,0.034479,0.136336,0.027778,182.633431,170.731542,0.041124,0.078999,0.194659,0.049555

## *All Experiments Compilation*

In [83]:
##################################################
# Compile All Global Experiments
##################################################

# paths to single, multi-scale, & multimodal compilations...
single_path = os.path.join(assets_dir, "single_class.csv")
ms_path = os.path.join(assets_dir, "multiscale_class.csv")
mm_path = os.path.join(assets_dir, "multimodal_class.csv")

# output path
output_path = os.path.join(assets_dir, 'compiled_class.csv')


##### compile data...
df_list = []
df_list.append(pd.read_csv(single_path))
df_list.append(pd.read_csv(ms_path))
df_list.append(pd.read_csv(mm_path))

df = pd.concat(df_list)
df.reset_index(drop=True, inplace=True)

df.to_csv(output_path, index=False)
df.head()

,model,encoder,input,class,gt_support (id),pred_support (id),gt_num_images (id),pred_num_images (id),tp (id),fp (id),...,macro_iou (cd),macro_dice (cd),macro_precision (cd),macro_recall (cd),mean_hd (cd),mean_hd95 (cd),micro_iou (cd),micro_dice (cd),micro_precision (cd),micro_recall (cd)
0,deeplabv3p,resnet50,dem,Qaf,10183.0,0.0,10.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000
1,deeplabv3p,resnet50,dem,Qal,8361713.0,7536136.0,947.0,928.0,5980234.0,1555902.0,...,0.137092,0.188426,0.314983,0.180292,141.442329,126.829787,0.228576,0.372099,0.608144,0.268055
2,deeplabv3p,resnet50,dem,Qat,388848.0,268789.0,61.0,60.0,94148.0,174641.0,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000
3,deeplabv3p,resnet50,dem,Qc,16237424.0,17202215.0,748.0,807.0,14663487.0,2538728.0,...,0.213697,0.275945,0.229029,0.435821,130.693717,111.436685,0.434113,0.605410,0.445544,0.944196
4,deeplabv3p,resnet50,dem,Qca,7202703.0,5861922.0,431.0,419.0,3971679.0,1890243.0,...,0.028692,0.045314,0.126181,0.039797,172.521181,158.150522,0.069393,0.129781,0.146740,0.116336

## *Visualizations*